In [1]:
import numpy as np

In [2]:
y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

# implement mean absolute error

In [3]:
def mae(y_predicted,y_true):
    total_error=0
    for yp,yt in zip(y_predicted,y_true):
        total_error+=abs(yp-yt)
    print("Total error is:",total_error)
    mae=total_error/len(y_predicted)
    print("Mean absolute erros is:",mae)
    return mae
mae(y_predicted,y_true)

Total error is: 2.5
Mean absolute erros is: 0.5


0.5

implement same thing using numpy in much easier way

In [7]:
np.mean(np.abs(y_true-y_predicted))

0.5

In [8]:
np.sum(np.abs(y_true-y_predicted))

2.5

# implement log loss or binary cross entropy

In [9]:
np.log([0])

<ipython-input-9-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
epsilon=1e-15

In [11]:
np.log(epsilon)

-34.538776394910684

In [12]:
y_predicted

array([1, 1, 0, 0, 1])

In [26]:
y_predicted_new=[max(epsilon,i) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [27]:
1-epsilon

0.999999999999999

In [31]:
y_predicted_new=[min(1-epsilon,i) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [33]:
y_predicted_new=np.array(y_predicted_new)

In [34]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [35]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

in single function

In [36]:
def log_loss(y_true,y_predicted):
    y_predicted_new=[max(epsilon,i) for i in y_predicted]
    y_predicted_new=[min(1-epsilon,i) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [37]:
log_loss(y_true,y_predicted)

17.2696280766844